[package]
name = "core-models"
description = "Models of the Rust core library"
version = "0.0.5"
readme = "readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rand = "0.10"
hax-lib.workspace = true
pastey = "0.2.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hax)'] }
