[package]
name = "libcrux-chacha20poly1305"
description = "Formally verified ChaCha20-Poly1305 AEAD library"
version = "0.0.6"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
libcrux-poly1305 = { version = "=0.0.4", path = "../poly1305/", features = [
    "expose-hacl",
] }
libcrux-hacl-rs = { version = "=0.0.4", path = "../../utils/hacl-rs/" }
libcrux-macros = { version = "=0.0.3", path = "../../utils/macros" }
libcrux-traits.workspace = true
libcrux-secrets.workspace = true

[dev-dependencies]
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
rand_core = { version = "0.9", features = ["os_rng"] }

[features]
check-secret-independence = ["libcrux-secrets/check-secret-independence"]
