[package]
name = "libcrux-sha2"
description = "Formally verified SHA2 hash library"
version = "0.0.5"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[features]
expose-hacl = []

[dependencies]
libcrux-hacl-rs = { version = "=0.0.4", path = "../../utils/hacl-rs/" }
libcrux-macros = { version = "=0.0.3", path = "../../utils/macros" }
libcrux-traits.workspace = true

[dev-dependencies]
hex = { version = "0.4.3" }
libcrux-traits = { workspace = true, features = ["generic-tests"] }
