[package]
description = "Digest library"
name = "libcrux-digest"
readme = "Readme.md"
version = "0.0.6-pre.2"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libcrux-blake2 = { workspace = true, optional = true }
libcrux-sha2 = { workspace = true, optional = true }
libcrux-sha3 = { workspace = true, optional = true }
libcrux-traits = { workspace = true, optional = true }

[features]
blake2 = ["dep:libcrux-blake2", "dep:libcrux-traits"]
default = ["blake2", "sha2", "sha3"]
sha2 = ["dep:libcrux-sha2", "dep:libcrux-traits"]
sha3 = ["dep:libcrux-sha3", "dep:libcrux-traits"]
