[package]
name = "libcrux-rsa"
description = "Formally verified RSA signature library"
version = "0.0.4"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[features]
expose-hacl = []

[dependencies]
libcrux-hacl-rs = { version = "=0.0.4", path = "../../utils/hacl-rs/" }
libcrux-traits.workspace = true
libcrux-macros = { version = "=0.0.3", path = "../../utils/macros" }
libcrux-sha2 = { workspace = true, features = [
    "expose-hacl",
] }

[dev-dependencies]
wycheproof = "0.6.0"
