[package]
name = "libcrux-rsa"
description = "Formally verified RSA signature library"
version = "0.0.5"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[features]
expose-hacl = []

[dependencies]
libcrux-hacl-rs.workspace = true
libcrux-traits.workspace = true
libcrux-macros.workspace = true
libcrux-sha2 = { workspace = true, features = [
    "expose-hacl",
] }

[dev-dependencies]
wycheproof = "0.6.0"
