[package]
name = "libcrux-ed25519"
description = "Formally verified ed25519 signature library"
version = "0.0.6-pre.1"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
libcrux-hacl-rs = { version = "=0.0.4", path = "../../utils/hacl-rs/" }
libcrux-sha2 = { workspace = true, features = [
    "expose-hacl",
] }
libcrux-macros = { version = "=0.0.3", path = "../../utils/macros" }
rand_core = { version = "0.9", optional = true }
tls_codec = { version = "0.4.2", features = ["derive"], optional = true }

[dev-dependencies]
hex = "0.4.3"
rand = { version = "0.9" }
wycheproof = "0.6.0"

[features]
rand = ["dep:rand_core"]
codec = ["tls_codec/std"]
