[package]
name = "libcrux-blake2"
description = "Formally verified blake2 hash library"
version = "0.0.6"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[features]
std = []
default = ["std"]

[dependencies]
libcrux-hacl-rs.workspace = true
libcrux-macros.workspace = true
libcrux-traits.workspace = true

[dev-dependencies]
criterion = "0.8"
rand = "0.10"
libcrux-traits = { workspace = true, features = ["generic-tests"] }

[[bench]]
name = "blake2"
harness = false
