[package]
authors.workspace = true
description = "Libcrux AES-GCM implementation"
edition.workspace = true
exclude = []
homepage.workspace = true
license.workspace = true
name = "libcrux-aesgcm"
readme = "README.md"
repository.workspace = true
version = "0.0.4"

[lib]
bench = false # so libtest doesn't eat the arguments to criterion

[dependencies]
libcrux-intrinsics.workspace = true
libcrux-platform.workspace = true
libcrux-traits.workspace = true
libcrux-secrets.workspace = true

rand = { version = "0.9", optional = true }

[features]
default = []
rand = ["dep:rand"]
simd128 = []
simd256 = []
std = []

[[bench]]
harness = false
name = "aesgcm"

[dev-dependencies]
aes-gcm = "0.10.3"
cavp = { version = "0.0.2", path = "../../../cavp" }
criterion = "0.5.1"
hex = "0.4.3"
pretty_env_logger = "0.5.0"
rand = "0.9"
rand_core = { version = "0.9" }
wycheproof = "0.6.0"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hax)', 'cfg(eurydice)'] }
