[package]
name = "libcrux-ecdsa"
description = "Formally verified ECDSA signature library"
readme = "Readme.md"
version = "0.0.6"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
libcrux-p256 = { workspace = true, default-features = true, features = [
    "expose-hacl",
] }
libcrux-sha2.workspace = true
rand = { version = "0.9", optional = true, default-features = false }

[features]
default = ["rand", "std"]
rand = ["dep:rand"]
std = ["rand?/std"]

[dev-dependencies]
rand_core = { version = "0.10" , features = ["os_rng"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
