[package]
description = "Formally verified ECDSA signature library"
name = "libcrux-ecdsa"
readme = "Readme.md"
version = "0.0.4"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libcrux-p256 = { version = "=0.0.4", path = "../p256", features = [
    "expose-hacl",
] }
libcrux-sha2 = { version = "=0.0.4", path = "../sha2" }
libcrux-secrets = { version = "=0.0.4", path = "../../utils/secrets" }
libcrux-traits = { version = "=0.0.4", path = "../../../traits" }
rand = { version = "0.9", optional = true, default-features = false }

[features]
default = ["rand", "std"]
rand = ["dep:rand"]
std = ["rand?/std"]
check-secret-independence = [
    "libcrux-secrets/check-secret-independence",
    "libcrux-traits/check-secret-independence",
]

[dev-dependencies]
rand_core = { version = "0.9", features = ["os_rng"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
