[package]
name = "libcrux-hkdf"
version = "0.0.4"
description = "Libcrux HKDF implementation"
readme = "Readme.md"

authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
path = "src/hkdf.rs"

[features]
check-secret-independence = ["libcrux-secrets/check-secret-independence"]

[dependencies]
libcrux-hmac = { version = "=0.0.4", path = "../../../libcrux-hmac", features = [
    "expose-hacl",
] }
libcrux-hacl-rs = { version = "=0.0.4", path = "../../../hacl-rs/" }
libcrux-secrets = { version = "0.0.4", path = "../../../secrets" }
